"""Generate awesome-stars README from GitHub starred repos."""
import json, os
from collections import OrderedDict
from urllib.request import Request, urlopen

USERNAME = "kelegele"
TOKEN = os.environ["GITHUB_TOKEN"]
PER_PAGE = 100

def fetch_page(page):
    url = f"https://api.github.com/users/{USERNAME}/starred?per_page={PER_PAGE}&page={page}"
    req = Request(url, headers={
        "Authorization": f"Bearer {TOKEN}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    })
    return json.loads(urlopen(req).read())

# Fetch all pages
repos = []
page = 1
while True:
    batch = fetch_page(page)
    if not batch:
        break
    repos.extend(batch)
    if len(batch) < PER_PAGE:
        break
    page += 1

print(f"Fetched {len(repos)} starred repos")

# Group by language
by_lang = {}
for r in repos:
    lang = r.get("language") or "Others"
    desc = (r.get("description") or "").replace("\n", " ").strip()[:200]
    if lang not in by_lang:
        by_lang[lang] = []
    by_lang[lang].append((r["full_name"], r["html_url"], desc))

by_lang = OrderedDict(sorted(by_lang.items(), key=lambda x: x[0]))

# Build README
lines = [
    "<!--lint disable awesome-contributing awesome-license awesome-list-item match-punctuation no-repeat-punctuation no-undefined-references awesome-spell-check-->",
    "# Awesome Stars [![Awesome](https://awesome.re/badge.svg)](https://github.com/sindresorhus/awesome)",
    "",
    "> A curated list of my GitHub stars! Generated by [starred](https://github.com/maguowei/starred).",
    "",
    "## Contents",
    "",
]

for lang in by_lang:
    anchor = '-'.join(lang.lower().split())
    lines.append(f'- [{lang}](#{anchor})')

lines.append("")

for lang, items in by_lang.items():
    lines.append(f'## {lang}')
    lines.append("")
    for name, url, desc in items:
        lines.append(f'- [{name}]({url}) - {desc}')
    lines.append("")

lines.extend([
    "## License",
    "",
    "[![CC0](http://mirrors.creativecommons.org/presskit/buttons/88x31/svg/cc-zero.svg)](https://creativecommons.org/publicdomain/zero/1.0/)",
    "",
    f"To the extent possible under law, [{USERNAME}](https://github.com/{USERNAME}) has waived all copyright and related or neighboring rights to this work.",
])

with open("README.md", "w") as f:
    f.write("\n".join(lines))

print(f"README.md generated ({len(repos)} repos, {len(by_lang)} languages)")
